server:
  port: 8282

# SERVICE_REGISTRY ----------------------------------------------------------------------------------------------------
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}@${random.int}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user-service?useSSL=false&useUnicode=true&characterEncoding=UTF-8}
    username: postgres
    password: myPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

redis:
  time-cache-seconds: 300
  prefix-user: user

