server:
  port: 8284

# SERVICE_REGISTRY ----------------------------------------------------------------------------------------------------
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}@${random.int}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://0.0.0.0:8761/eureka}

spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://0.0.0.0:5432/order-service?useSSL=false&useUnicode=true&characterEncoding=UTF-8}
    username: postgres
    password: myPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

url-internal:
  is-stock-product: http://product-service/internal-api/product/stock
